---

  - apt:
      name: rfkill
      state: present
    tags:
      - section3
      - section3.7
      - lvl.1.server
      - lvl.2.workstation
      - not.scored
      
  - name: 3.7 Ensure wireless interfaces are disabled (Not Scored)
    command: rfkill block wifi
    when: false
    tags:
      - section3
      - section3.7
      - lvl.1.server
      - lvl.2.workstation
      - not.scored
      
