---

  - include: section_03_level1.yml
    tags:
      - section03
      - level1

  - include: section_03_level2.yml
    tags:
      - section03
      - level2

  - include: section_03_level3.yml
    tags:
      - section03
      - level3

  - include: section_03_level4.yml
    tags:
      - section03
      - level4

  - include: section_03_level5.yml
    tags:
      - section03
      - level5

  - include: section_03_level6.yml
    tags:
      - section03
      - level6

  - include: section_03_level7.yml
    tags:
      - section03
      - level7
